/**
 * Reference Template — React Project Scaffolder
 * 
 * This file is a reference implementation that the React Developer agent
 * can look at for project structure, component patterns, and CSS setup.
 * It can also be run directly to scaffold a blank project skeleton.
 * 
 * The agent doesn't HAVE to use this — it can write everything from scratch.
 * But this gives it a proven starting point.
 */

import fs from 'fs-extra';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

/**
 * Scaffold the complete React tutorial project from a LearningBrief.
 * In agentic mode, each file's content is generated by the agent pipeline.
 * In CLI mode, this copies from templates and injects the brief's config.
 */
export async function scaffoldProject(brief) {
  const outputDir = path.resolve(brief.output);
  await fs.ensureDir(outputDir);

  // Write package.json
  await fs.writeJson(path.join(outputDir, 'package.json'), buildPackageJson(brief), { spaces: 2 });

  // Write Vite config
  await fs.writeFile(path.join(outputDir, 'vite.config.js'), buildViteConfig());

  // Write Tailwind configs
  await fs.writeFile(path.join(outputDir, 'tailwind.config.js'), buildTailwindConfig(brief));
  await fs.writeFile(path.join(outputDir, 'postcss.config.js'), buildPostCSSConfig());

  // Write index.html
  await fs.writeFile(path.join(outputDir, 'index.html'), buildIndexHtml(brief));

  // Create src directories
  const srcDirs = [
    'src', 'src/components', 'src/components/layout', 'src/components/lesson',
    'src/components/quiz', 'src/components/progress', 'src/components/ui',
    'src/hooks', 'src/data', 'src/data/lessons', 'src/data/quizzes',
    'src/lib', 'src/pages'
  ];
  for (const dir of srcDirs) {
    await fs.ensureDir(path.join(outputDir, dir));
  }

  // Write main entry files
  await fs.writeFile(path.join(outputDir, 'src/main.jsx'), buildMainJsx());
  await fs.writeFile(path.join(outputDir, 'src/index.css'), buildGlobalCSS(brief));
  await fs.writeFile(path.join(outputDir, 'src/App.jsx'), buildAppJsx());

  // Write placeholder syllabus data
  await fs.writeJson(
    path.join(outputDir, 'src/data/syllabus.json'),
    buildPlaceholderSyllabus(brief),
    { spaces: 2 }
  );

  // Write hooks
  await fs.writeFile(path.join(outputDir, 'src/hooks/useProgress.js'), buildUseProgress());
  await fs.writeFile(path.join(outputDir, 'src/hooks/useQuiz.js'), buildUseQuiz());

  // Write lib files
  await fs.writeFile(path.join(outputDir, 'src/lib/constants.js'), buildLibConstants(brief));
  await fs.writeFile(path.join(outputDir, 'src/lib/utils.js'), buildLibUtils());

  return outputDir;
}

// ─── FILE BUILDERS ──────────────────────────────────────────────

function buildPackageJson(brief) {
  const slug = brief.topic.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
  return {
    name: `syllabus-${slug}`,
    private: true,
    version: '1.0.0',
    type: 'module',
    scripts: {
      dev: 'vite',
      build: 'vite build',
      preview: 'vite preview'
    },
    dependencies: {
      'react': '^18.3.1',
      'react-dom': '^18.3.1',
      'react-router-dom': '^6.28.0',
      'framer-motion': '^11.11.0',
      'prismjs': '^1.29.0',
      'lucide-react': '^0.453.0'
    },
    devDependencies: {
      '@vitejs/plugin-react': '^4.3.0',
      'vite': '^6.0.0',
      'tailwindcss': '^3.4.0',
      '@tailwindcss/typography': '^0.5.15',
      'autoprefixer': '^10.4.20',
      'postcss': '^8.4.47'
    }
  };
}

function buildViteConfig() {
  return `import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
  server: { port: 3000, open: true }
})
`;
}

function buildTailwindConfig(brief) {
  return `/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        surface: 'var(--surface)',
        primary: 'var(--primary)',
        accent: 'var(--accent)',
      },
      fontFamily: {
        display: ['Space Grotesk', 'sans-serif'],
        body: ['IBM Plex Sans', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      }
    },
  },
  plugins: [require('@tailwindcss/typography')],
}
`;
}

function buildPostCSSConfig() {
  return `export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
`;
}

function buildIndexHtml(brief) {
  return `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Syllabus — ${brief.topic}</title>
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500&family=Space+Grotesk:wght@500;600;700&display=swap" rel="stylesheet" />
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
`;
}

function buildMainJsx() {
  return `import React from 'react'
import ReactDOM from 'react-dom/client'
import { BrowserRouter } from 'react-router-dom'
import App from './App'
import './index.css'

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <BrowserRouter>
      <App />
    </BrowserRouter>
  </React.StrictMode>
)
`;
}

function buildGlobalCSS(brief) {
  const themes = {
    dark: `--bg: #0a0e1a; --surface: #131829; --surface-hover: #1a2035; --primary: #6366f1; --primary-hover: #818cf8; --accent: #22d3ee; --success: #34d399; --warning: #fbbf24; --error: #f87171; --text: #e2e8f0; --text-secondary: #94a3b8; --text-muted: #64748b; --border: #1e293b; --code-bg: #0f1320;`,
    light: `--bg: #fafaf9; --surface: #ffffff; --surface-hover: #f5f5f4; --primary: #2563eb; --primary-hover: #3b82f6; --accent: #0891b2; --success: #16a34a; --warning: #d97706; --error: #dc2626; --text: #1c1917; --text-secondary: #57534e; --text-muted: #a8a29e; --border: #e7e5e4; --code-bg: #f5f5f4;`,
    terminal: `--bg: #0c0c0c; --surface: #1a1a1a; --surface-hover: #222222; --primary: #22c55e; --primary-hover: #4ade80; --accent: #a3e635; --success: #22c55e; --warning: #eab308; --error: #ef4444; --text: #d4d4d4; --text-secondary: #a3a3a3; --text-muted: #737373; --border: #2a2a2a; --code-bg: #111111;`,
    notebook: `--bg: #fffbeb; --surface: #ffffff; --surface-hover: #fef9c3; --primary: #7c3aed; --primary-hover: #8b5cf6; --accent: #f59e0b; --success: #10b981; --warning: #f59e0b; --error: #ef4444; --text: #292524; --text-secondary: #57534e; --text-muted: #a8a29e; --border: #e7e5e4; --code-bg: #f5f5f0;`
  };

  const themeVars = themes[brief.theme] || themes.dark;

  return `@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  ${themeVars}
}

body {
  margin: 0;
  background: var(--bg);
  color: var(--text);
  font-family: 'IBM Plex Sans', sans-serif;
  -webkit-font-smoothing: antialiased;
  line-height: 1.75;
}

h1, h2, h3, h4 {
  font-family: 'Space Grotesk', sans-serif;
  font-weight: 600;
  line-height: 1.3;
}

code, pre {
  font-family: 'JetBrains Mono', monospace;
}

pre {
  background: var(--code-bg);
  border-radius: 12px;
  padding: 1.25rem;
  overflow-x: auto;
  font-size: 0.9rem;
  line-height: 1.6;
  border: 1px solid var(--border);
}

::-webkit-scrollbar {
  width: 6px;
  height: 6px;
}

::-webkit-scrollbar-track {
  background: var(--bg);
}

::-webkit-scrollbar-thumb {
  background: var(--border);
  border-radius: 3px;
}

::-webkit-scrollbar-thumb:hover {
  background: var(--text-muted);
}

@media (prefers-reduced-motion: reduce) {
  *, *::before, *::after {
    animation-duration: 0.01ms !important;
    transition-duration: 0.01ms !important;
  }
}

/* Focus styles for accessibility */
*:focus-visible {
  outline: 2px solid var(--primary);
  outline-offset: 2px;
  border-radius: 4px;
}

/* Skip to main content link */
.skip-link {
  position: absolute;
  top: -100px;
  left: 0;
  padding: 0.5rem 1rem;
  background: var(--primary);
  color: white;
  z-index: 100;
  transition: top 0.2s;
}

.skip-link:focus {
  top: 0;
}
`;
}

function buildAppJsx() {
  return `import { Routes, Route } from 'react-router-dom'
import { useState, createContext } from 'react'
import syllabus from './data/syllabus.json'

// Context for global state
export const AppContext = createContext(null)

export default function App() {
  const [progress, setProgress] = useState(() => {
    try {
      const saved = localStorage.getItem('syllabus-progress')
      return saved ? JSON.parse(saved) : {
        completedLessons: [],
        quizScores: {},
        currentLesson: null,
        startedAt: new Date().toISOString(),
        totalTimeSpent: 0
      }
    } catch { return { completedLessons: [], quizScores: {}, currentLesson: null, startedAt: new Date().toISOString(), totalTimeSpent: 0 } }
  })

  const [sidebarOpen, setSidebarOpen] = useState(true)

  const markComplete = (lessonId) => {
    setProgress(prev => {
      const updated = {
        ...prev,
        completedLessons: [...new Set([...prev.completedLessons, lessonId])],
        currentLesson: lessonId
      }
      localStorage.setItem('syllabus-progress', JSON.stringify(updated))
      return updated
    })
  }

  const totalLessons = syllabus.modules.reduce((sum, m) => sum + m.lessons.length, 0)
  const completionPct = Math.round((progress.completedLessons.length / totalLessons) * 100)

  return (
    <AppContext.Provider value={{ syllabus, progress, markComplete, sidebarOpen, setSidebarOpen }}>
      <a href="#main-content" className="skip-link">Skip to main content</a>
      
      <div className="flex min-h-screen">
        {/* Sidebar */}
        <aside
          className="w-72 border-r flex-shrink-0 flex flex-col transition-all duration-300 overflow-y-auto"
          style={{ 
            borderColor: 'var(--border)', 
            background: 'var(--surface)',
            marginLeft: sidebarOpen ? 0 : '-18rem'
          }}
          role="navigation"
          aria-label="Course navigation"
        >
          <div className="p-5 border-b" style={{ borderColor: 'var(--border)' }}>
            <h1 className="text-lg font-display font-bold" style={{ color: 'var(--primary)' }}>
              � Syllabus
            </h1>
            <p className="text-sm mt-1" style={{ color: 'var(--text-muted)' }}>
              {syllabus.title}
            </p>
          </div>

          {/* Progress ring */}
          <div className="p-5 flex items-center gap-4 border-b" style={{ borderColor: 'var(--border)' }}>
            <svg width="48" height="48" viewBox="0 0 48 48">
              <circle cx="24" cy="24" r="20" fill="none" stroke="var(--border)" strokeWidth="4" />
              <circle
                cx="24" cy="24" r="20" fill="none"
                stroke="var(--primary)" strokeWidth="4"
                strokeDasharray={2 * Math.PI * 20}
                strokeDashoffset={2 * Math.PI * 20 * (1 - completionPct / 100)}
                strokeLinecap="round"
                transform="rotate(-90 24 24)"
                style={{ transition: 'stroke-dashoffset 0.6s ease' }}
              />
              <text x="24" y="24" textAnchor="middle" dominantBaseline="central"
                fill="var(--text)" fontSize="11" fontWeight="600" fontFamily="Space Grotesk">
                {completionPct}%
              </text>
            </svg>
            <div>
              <div className="text-sm font-medium" style={{ color: 'var(--text)' }}>
                {progress.completedLessons.length} / {totalLessons}
              </div>
              <div className="text-xs" style={{ color: 'var(--text-muted)' }}>lessons done</div>
            </div>
          </div>

          {/* Module list */}
          <nav className="flex-1 p-3">
            {syllabus.modules.map((mod, mi) => (
              <div key={mod.id} className="mb-2">
                <div className="flex items-center gap-2 px-3 py-2 rounded-lg text-sm font-medium"
                  style={{ color: 'var(--text-secondary)' }}>
                  <span className="w-5 h-5 rounded-full text-xs flex items-center justify-center font-bold"
                    style={{ background: 'var(--primary)', color: 'white', opacity: 0.8 }}>
                    {mi + 1}
                  </span>
                  {mod.title}
                </div>
                <div className="ml-6 border-l pl-3" style={{ borderColor: 'var(--border)' }}>
                  {mod.lessons.map(les => {
                    const done = progress.completedLessons.includes(les.id)
                    return (
                      <button
                        key={les.id}
                        onClick={() => markComplete(les.id)}
                        className="w-full text-left px-3 py-1.5 rounded text-sm flex items-center gap-2 transition-colors"
                        style={{ 
                          color: done ? 'var(--success)' : 'var(--text-muted)',
                          background: progress.currentLesson === les.id ? 'var(--surface-hover)' : 'transparent'
                        }}
                        aria-current={progress.currentLesson === les.id ? 'page' : undefined}
                      >
                        <span className="text-xs">{done ? '✓' : '○'}</span>
                        {les.title}
                      </button>
                    )
                  })}
                </div>
              </div>
            ))}
          </nav>
        </aside>

        {/* Main content */}
        <main id="main-content" className="flex-1 overflow-y-auto">
          {/* Top bar */}
          <header className="sticky top-0 z-10 backdrop-blur-md border-b px-6 py-3 flex items-center justify-between"
            style={{ borderColor: 'var(--border)', background: 'color-mix(in srgb, var(--bg) 85%, transparent)' }}>
            <button 
              onClick={() => setSidebarOpen(!sidebarOpen)}
              className="p-2 rounded-lg transition-colors"
              style={{ color: 'var(--text-muted)' }}
              aria-label={sidebarOpen ? 'Close sidebar' : 'Open sidebar'}
            >
              ☰
            </button>
            <div className="flex-1 mx-6">
              <div className="h-1.5 rounded-full overflow-hidden" style={{ background: 'var(--border)' }}>
                <div
                  className="h-full rounded-full transition-all duration-500"
                  style={{ background: 'var(--primary)', width: completionPct + '%' }}
                  role="progressbar"
                  aria-valuenow={completionPct}
                  aria-valuemin={0}
                  aria-valuemax={100}
                  aria-label="Course progress"
                />
              </div>
            </div>
            <span className="text-sm font-medium" style={{ color: 'var(--text-muted)' }}>
              {completionPct}% complete
            </span>
          </header>

          {/* Content area */}
          <div className="max-w-3xl mx-auto px-6 py-10">
            <div className="mb-12">
              <h1 className="text-4xl font-display font-bold mb-4" style={{ color: 'var(--text)' }}>
                {syllabus.title}
              </h1>
              <p className="text-lg" style={{ color: 'var(--text-secondary)' }}>
                {syllabus.description}
              </p>
              <div className="flex gap-3 mt-6 flex-wrap">
                <span className="px-3 py-1 rounded-full text-sm font-medium"
                  style={{ background: 'var(--surface)', border: '1px solid var(--border)', color: 'var(--primary)' }}>
                  {syllabus.difficulty}
                </span>
                <span className="px-3 py-1 rounded-full text-sm"
                  style={{ background: 'var(--surface)', border: '1px solid var(--border)', color: 'var(--text-muted)' }}>
                  ⏱ {syllabus.totalDuration}
                </span>
                <span className="px-3 py-1 rounded-full text-sm"
                  style={{ background: 'var(--surface)', border: '1px solid var(--border)', color: 'var(--text-muted)' }}>
                  📚 {syllabus.modules.length} modules
                </span>
              </div>
            </div>

            {/* Module cards */}
            {syllabus.modules.map((mod, mi) => {
              const modLessons = mod.lessons.length
              const modDone = mod.lessons.filter(l => progress.completedLessons.includes(l.id)).length
              const modPct = Math.round((modDone / modLessons) * 100)

              return (
                <div key={mod.id} className="mb-6 rounded-2xl border p-6 transition-all"
                  style={{ 
                    borderColor: modPct === 100 ? 'var(--success)' : 'var(--border)', 
                    background: 'var(--surface)',
                    opacity: modPct === 100 ? 0.85 : 1 
                  }}>
                  <div className="flex items-start justify-between mb-3">
                    <div>
                      <span className="text-xs font-medium px-2 py-0.5 rounded"
                        style={{ background: 'var(--primary)', color: 'white', opacity: 0.9 }}>
                        Module {mi + 1}
                      </span>
                      <h2 className="text-xl font-display font-bold mt-2" style={{ color: 'var(--text)' }}>
                        {mod.title}
                      </h2>
                    </div>
                    {modPct === 100 && (
                      <span className="text-2xl" role="img" aria-label="Completed">✅</span>
                    )}
                  </div>
                  <p className="text-sm mb-4" style={{ color: 'var(--text-secondary)' }}>
                    {mod.description}
                  </p>
                  <div className="flex items-center gap-3">
                    <div className="flex-1 h-1.5 rounded-full" style={{ background: 'var(--border)' }}>
                      <div className="h-full rounded-full transition-all duration-300"
                        style={{ background: modPct === 100 ? 'var(--success)' : 'var(--primary)', width: modPct + '%' }} />
                    </div>
                    <span className="text-sm font-medium" style={{ color: 'var(--text-muted)' }}>
                      {modDone}/{modLessons}
                    </span>
                  </div>
                  <div className="mt-4 flex gap-2 flex-wrap">
                    <span className="text-xs" style={{ color: 'var(--text-muted)' }}>⏱ {mod.duration}</span>
                    {mod.lessons.some(l => l.hasCodeExample) && (
                      <span className="text-xs" style={{ color: 'var(--accent)' }}>💻 Code examples</span>
                    )}
                    {mod.quiz && (
                      <span className="text-xs" style={{ color: 'var(--warning)' }}>🧩 Quiz</span>
                    )}
                  </div>
                </div>
              )
            })}
          </div>
        </main>
      </div>
    </AppContext.Provider>
  )
}
`;
}

function buildPlaceholderSyllabus(brief) {
  return {
    title: `Mastering ${brief.topic}`,
    description: `A comprehensive, interactive ${brief.style} tutorial on ${brief.topic}. Built with Syllabus.`,
    totalDuration: '6-8 hours',
    difficulty: brief.depth,
    prerequisites: [
      { topic: 'Basic programming', level: 'comfortable' },
    ],
    modules: [
      {
        id: 'mod-01',
        title: 'Introduction & Foundations',
        description: `What ${brief.topic} is, why it matters, and the core mental models you need.`,
        duration: '45 min',
        lessons: [
          { id: 'les-01-01', title: 'The Big Picture', type: 'conceptual', duration: '15 min', hasCodeExample: false, hasDiagram: true },
          { id: 'les-01-02', title: 'Key Concepts & Vocabulary', type: 'conceptual', duration: '15 min', hasCodeExample: false, hasDiagram: true },
          { id: 'les-01-03', title: 'Setting Up Your Environment', type: 'hands-on', duration: '15 min', hasCodeExample: true, hasDiagram: false },
        ],
        quiz: { questionCount: 3, types: ['multiple-choice', 'true-false'] }
      },
      {
        id: 'mod-02',
        title: 'Core Mechanics',
        description: 'The fundamental techniques and patterns that everything else builds on.',
        duration: '60 min',
        lessons: [
          { id: 'les-02-01', title: 'How It Works Under the Hood', type: 'conceptual', duration: '20 min', hasCodeExample: true, hasDiagram: true },
          { id: 'les-02-02', title: 'Your First Implementation', type: 'hands-on', duration: '20 min', hasCodeExample: true, hasDiagram: false },
          { id: 'les-02-03', title: 'Common Patterns & Best Practices', type: 'hands-on', duration: '20 min', hasCodeExample: true, hasDiagram: false },
        ],
        quiz: { questionCount: 4, types: ['multiple-choice', 'code-completion'] }
      },
      {
        id: 'mod-03',
        title: 'Intermediate Techniques',
        description: 'Level up with more advanced patterns and real-world applications.',
        duration: '60 min',
        lessons: [
          { id: 'les-03-01', title: 'Advanced Configuration', type: 'hands-on', duration: '20 min', hasCodeExample: true, hasDiagram: true },
          { id: 'les-03-02', title: 'Performance & Optimization', type: 'conceptual', duration: '20 min', hasCodeExample: true, hasDiagram: true },
          { id: 'les-03-03', title: 'Debugging & Troubleshooting', type: 'hands-on', duration: '20 min', hasCodeExample: true, hasDiagram: false },
        ],
        quiz: { questionCount: 4, types: ['multiple-choice', 'code-completion', 'ordering'] }
      },
      {
        id: 'mod-04',
        title: 'Real-World Applications',
        description: 'Apply everything to production scenarios and real projects.',
        duration: '60 min',
        lessons: [
          { id: 'les-04-01', title: 'Building a Real Project', type: 'hands-on', duration: '30 min', hasCodeExample: true, hasDiagram: true },
          { id: 'les-04-02', title: 'Testing & Validation', type: 'hands-on', duration: '15 min', hasCodeExample: true, hasDiagram: false },
          { id: 'les-04-03', title: 'Deployment & Production', type: 'hands-on', duration: '15 min', hasCodeExample: true, hasDiagram: true },
        ],
        quiz: { questionCount: 3, types: ['scenario', 'coding-challenge'] }
      },
      {
        id: 'mod-05',
        title: 'Advanced Deep Dive',
        description: 'Push your understanding to expert level with edge cases and advanced patterns.',
        duration: '60 min',
        lessons: [
          { id: 'les-05-01', title: 'Edge Cases & Gotchas', type: 'conceptual', duration: '20 min', hasCodeExample: true, hasDiagram: false },
          { id: 'les-05-02', title: 'Scaling & Architecture', type: 'conceptual', duration: '20 min', hasCodeExample: false, hasDiagram: true },
          { id: 'les-05-03', title: 'Advanced Patterns', type: 'hands-on', duration: '20 min', hasCodeExample: true, hasDiagram: true },
        ],
        quiz: { questionCount: 4, types: ['multiple-choice', 'scenario'] }
      },
      ...(brief.style === 'interview-prep' ? [{
        id: 'mod-06',
        title: 'Interview Preparation',
        description: 'Common interview questions, mock scenarios, and how to explain concepts clearly.',
        duration: '45 min',
        lessons: [
          { id: 'les-06-01', title: 'Top Interview Questions', type: 'conceptual', duration: '15 min', hasCodeExample: false, hasDiagram: false },
          { id: 'les-06-02', title: 'System Design Scenarios', type: 'conceptual', duration: '15 min', hasCodeExample: false, hasDiagram: true },
          { id: 'les-06-03', title: 'Mock Interview Simulator', type: 'hands-on', duration: '15 min', hasCodeExample: false, hasDiagram: false },
        ],
        quiz: { questionCount: 5, types: ['scenario', 'multiple-choice'] }
      }] : [])
    ]
  };
}

function buildUseProgress() {
  return `import { useState, useEffect, useCallback } from 'react'

const STORAGE_KEY = 'syllabus-progress'

const defaultProgress = {
  completedLessons: [],
  quizScores: {},
  currentLesson: null,
  startedAt: new Date().toISOString(),
  totalTimeSpent: 0,
  streakDays: 0
}

export function useProgress() {
  const [progress, setProgress] = useState(() => {
    try {
      const saved = localStorage.getItem(STORAGE_KEY)
      return saved ? JSON.parse(saved) : defaultProgress
    } catch {
      return defaultProgress
    }
  })

  // Debounced save to localStorage
  useEffect(() => {
    const timeout = setTimeout(() => {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(progress))
    }, 500)
    return () => clearTimeout(timeout)
  }, [progress])

  const markComplete = useCallback((lessonId) => {
    setProgress(prev => ({
      ...prev,
      completedLessons: [...new Set([...prev.completedLessons, lessonId])],
      currentLesson: lessonId
    }))
  }, [])

  const saveQuizScore = useCallback((moduleId, score, total) => {
    setProgress(prev => ({
      ...prev,
      quizScores: {
        ...prev.quizScores,
        [moduleId]: {
          score,
          total,
          attempts: (prev.quizScores[moduleId]?.attempts || 0) + 1,
          lastAttempt: new Date().toISOString()
        }
      }
    }))
  }, [])

  const resetProgress = useCallback(() => {
    setProgress(defaultProgress)
    localStorage.removeItem(STORAGE_KEY)
  }, [])

  return { progress, markComplete, saveQuizScore, resetProgress }
}
`;
}

function buildUseQuiz() {
  return `import { useState, useCallback } from 'react'

export function useQuiz(questions = []) {
  const [currentIndex, setCurrentIndex] = useState(0)
  const [answers, setAnswers] = useState({})
  const [showExplanation, setShowExplanation] = useState(false)
  const [completed, setCompleted] = useState(false)

  const currentQuestion = questions[currentIndex] || null

  const submitAnswer = useCallback((questionId, answer) => {
    setAnswers(prev => ({ ...prev, [questionId]: answer }))
    setShowExplanation(true)
  }, [])

  const nextQuestion = useCallback(() => {
    setShowExplanation(false)
    if (currentIndex < questions.length - 1) {
      setCurrentIndex(prev => prev + 1)
    } else {
      setCompleted(true)
    }
  }, [currentIndex, questions.length])

  const getScore = useCallback(() => {
    let correct = 0
    for (const q of questions) {
      if (q.type === 'multiple-choice') {
        const selected = answers[q.id]
        const correctOption = q.options.find(o => o.correct)
        if (selected === correctOption?.id) correct++
      }
    }
    return { correct, total: questions.length }
  }, [answers, questions])

  const reset = useCallback(() => {
    setCurrentIndex(0)
    setAnswers({})
    setShowExplanation(false)
    setCompleted(false)
  }, [])

  return {
    currentQuestion,
    currentIndex,
    answers,
    showExplanation,
    completed,
    submitAnswer,
    nextQuestion,
    getScore,
    reset
  }
}
`;
}

function buildLibConstants(brief) {
  return `export const COURSE_TITLE = '${brief.topic.replace(/'/g, "\\'")}';
export const COURSE_STYLE = '${brief.style}';
export const COURSE_DEPTH = '${brief.depth}';
export const COURSE_THEME = '${brief.theme}';
`;
}

function buildLibUtils() {
  return `/**
 * Format duration in minutes to human-readable string
 */
export function formatDuration(minutes) {
  if (minutes < 60) return \`\${minutes} min\`;
  const hours = Math.floor(minutes / 60);
  const mins = minutes % 60;
  return mins > 0 ? \`\${hours}h \${mins}m\` : \`\${hours}h\`;
}

/**
 * Calculate percentage, clamped 0-100
 */
export function percentage(current, total) {
  if (total === 0) return 0;
  return Math.min(100, Math.max(0, Math.round((current / total) * 100)));
}

/**
 * Slugify a string for use in URLs
 */
export function slugify(str) {
  return str
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

/**
 * Simple debounce
 */
export function debounce(fn, ms) {
  let timer;
  return (...args) => {
    clearTimeout(timer);
    timer = setTimeout(() => fn(...args), ms);
  };
}
`;
}
